import Link from "next/link";
import { ArrowUpRight, Check, Layers3, MoveRight } from "lucide-react";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { Hero } from "@/components/hero";
import { Reveal } from "@/components/motion";
import { services } from "@/lib/site-data";

export default function Home() { return <><Header/><main><Hero/>
  <section id="services" className="section border-t border-white/10 bg-[#081421]"><div className="shell"><Reveal><p className="eyebrow">What we do</p><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><h2 className="section-title">One partner.<br/>Every digital edge.</h2><p className="max-w-md leading-7 text-slate-400">We bring strategy, creative thinking and deep technical execution under one roof—so your business moves with speed and clarity.</p></div></Reveal><div className="mt-16 grid gap-px overflow-hidden rounded-3xl bg-white/10 md:grid-cols-2 lg:grid-cols-3">{services.map((s,i)=><Reveal key={s.slug} delay={i*.04}><article className="service-card"><div className="flex items-start justify-between"><s.icon size={34} strokeWidth={1.5} className="text-aqua"/><span className="font-mono text-xs text-slate-600">{s.number}</span></div><h3 className="mt-20 font-display text-2xl">{s.title}</h3><p className="mt-4 text-sm leading-7 text-slate-400">{s.description}</p><div className="mt-7 flex flex-wrap gap-2">{s.tags.map(t=><span key={t} className="rounded-full border border-white/10 px-3 py-1 text-[10px] uppercase tracking-wider text-slate-400">{t}</span>)}</div></article></Reveal>)}</div></div></section>
  <section id="work" className="section overflow-hidden"><div className="shell grid gap-14 lg:grid-cols-2 lg:items-center"><Reveal><div className="relative min-h-[520px] overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-[#112d47] via-[#0d1a31] to-[#271853] p-8"><div className="absolute -right-16 -top-16 h-72 w-72 rounded-full bg-electric/30 blur-3xl"/><div className="relative rounded-2xl border border-white/15 bg-ink/70 p-5 backdrop-blur"><div className="flex gap-2"><i className="h-2 w-2 rounded-full bg-red-400"/><i className="h-2 w-2 rounded-full bg-yellow-300"/><i className="h-2 w-2 rounded-full bg-aqua"/></div><div className="mt-12 grid gap-4 sm:grid-cols-[1fr_160px]"><div className="h-48 rounded-xl bg-gradient-to-br from-electric/70 to-purple-600/40 p-6"><Layers3/><p className="mt-16 font-display text-xl">Systems built to scale.</p></div><div className="space-y-4"><div className="h-20 rounded-xl bg-white/10"/><div className="h-32 rounded-xl bg-aqua/10"/></div></div></div><div className="absolute bottom-8 left-8 rounded-full border border-white/15 bg-white/10 px-5 py-3 text-xs tracking-widest backdrop-blur">DESIGN × ENGINEERING</div></div></Reveal><Reveal><p className="eyebrow">Built differently</p><h2 className="section-title">Your goals lead.<br/>Technology follows.</h2><p className="mt-8 max-w-lg text-lg leading-8 text-slate-400">We do not sell trendy tools. We identify the shortest path from your challenge to a valuable outcome, then build it beautifully.</p><ul className="mt-9 space-y-4">{["Senior-level thinking on every engagement","Transparent milestones and communication","Performance, accessibility and security by default","Designed for ownership—not dependency"].map(x=><li key={x} className="flex items-center gap-3 text-sm text-slate-300"><span className="grid h-6 w-6 place-items-center rounded-full bg-aqua/10 text-aqua"><Check size={14}/></span>{x}</li>)}</ul><Link href="/about" className="mt-10 inline-flex items-center gap-3 font-bold">How we work <MoveRight/></Link></Reveal></div></section>
  <section id="process" className="section bg-[#f2f5f9] text-ink"><div className="shell"><Reveal><p className="eyebrow !text-slate-500">Our process</p><h2 className="section-title">Clarity at every step.</h2></Reveal><div className="mt-16 grid gap-10 md:grid-cols-4">{[["01","Discover","We listen, challenge assumptions and define the outcome."],["02","Design","We shape a clear strategy and an experience people value."],["03","Build","We engineer, integrate and test with disciplined execution."],["04","Evolve","We launch, learn and continuously improve performance."]].map(([n,t,d])=><Reveal key={n}><div className="border-t border-ink/20 pt-6"><span className="font-mono text-xs text-electric">{n}</span><h3 className="mt-10 font-display text-2xl">{t}</h3><p className="mt-4 text-sm leading-7 text-slate-600">{d}</p></div></Reveal>)}</div></div></section>
  <section className="section relative overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_50%,#4f7cff28,transparent_42%)]"/><Reveal className="shell relative text-center"><p className="eyebrow">Have a challenge in mind?</p><h2 className="mx-auto mt-6 max-w-4xl font-display text-[clamp(3rem,7vw,7rem)] leading-[.95] tracking-[-.055em]">Let’s build what moves you forward.</h2><Link className="button mt-10" href="/contact">Start the conversation <ArrowUpRight size={18}/></Link></Reveal></section>
  </main><Footer/></> }
